apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-hkdq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-hkdq
    app.kubernetes.io/part-of: ci1t-830-0051-app
  name: devfile-sample-hkdq
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-hkdq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-hkdq
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0051-tenant/ci1t-830-0051-app/devfile-sample-hkdq@sha256:1326dfebeedec2ddd8cc6f18609af26c66ae4d8ee8b1fc18c59cab0d5ea63c3b
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
